import{a as w,S as v,i as n}from"./assets/vendor-DnBR8w-b.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))r(o);new MutationObserver(o=>{for(const s of o)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&r(d)}).observe(document,{childList:!0,subtree:!0});function a(o){const s={};return o.integrity&&(s.integrity=o.integrity),o.referrerPolicy&&(s.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?s.credentials="include":o.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(o){if(o.ep)return;o.ep=!0;const s=a(o);fetch(o.href,s)}})();async function y(e,t=1){const a={key:"49512194-f753c2f34a7e7dbbd609db53f",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15};return await w.get("https://pixabay.com/api/",{params:a})}function g(e,t){const a=t.map(r=>`<li class="gallery-item">
    <a class="image-link" href="${r.largeImageURL}"><img class="image" src="${r.webformatURL}" alt="${r.tags}" title=""/></a>
    <ul class="image-descr-list">
<li class="descr-item">Likes<span class="descr-span">${r.likes}</span></li>
<li class="descr-item">Views<span class="descr-span">${r.views}</span></li>
<li class="descr-item">Comments<span class="descr-span">${r.comments}</span></li>
<li class="descr-item">Downloads<span class="descr-span">${r.downloads}</span></li>
    </ul>
    </li>`).join("");e.insertAdjacentHTML("beforeend",a),S()}const q=new v(".gallery-item a",{captionsData:"alt",captionDelay:250});function S(){q.refresh()}function B(e){e.innerHTML=""}function h(){const e=document.querySelector(".loader");e.style.display="flex"}function i(){const e=document.querySelector(".loader");e.style.display="none"}function b(){document.querySelector(".load-more-btn").classList.remove("visually-hidden")}function L(){document.querySelector(".load-more-btn").classList.add("visually-hidden")}const u=document.querySelector(".gallery"),f=document.querySelector(".form"),m=f.elements[0];m.classList.add("input");const M=f.elements[1];M.classList.add("button");const R=document.querySelector(".load-more-btn");let l=null,p=null,c=null;f.addEventListener("submit",P);async function P(e){if(e.preventDefault(),B(u),L(),h(),c=m.value,l=1,c===""){i(),n.error({message:"Write your something you want to see",position:"topRight"});return}try{const t=await y(c,l);if(t.data.hits.length===0){n.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"}),i();return}else{g(u,t.data.hits);let r=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r.height*2,behavior:"smooth"}),p=Math.ceil(t.data.totalHits/15),l<p?b():n.info({position:"bottomCenter",message:"We're sorry, but you've reached the end of search results."})}}catch{n.error({message:"Bad request",position:"topRight"})}i(),m.value=""}R.addEventListener("click",$);async function $(e){e.preventDefault(),L(),h(),l+=1;try{const t=await y(c,l);g(u,t.data.hits);let r=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r.height*2,behavior:"smooth"}),l<p?b():n.info({position:"bottomCenter",message:"We're sorry, but you've reached the end of search results."})}catch{n.error({message:"Bad request",position:"topRight"})}i()}
//# sourceMappingURL=index.js.map
